### ISSUE TITLE
shodanidb: command not found

### ISSUE THREAD

**Issue by Lark-3301** [s4hm4d/shodanidb#1]
Why is this happening? The console doesn´t recognize "shodanidb"

<img width="821" alt="image" src="https://user-images.githubusercontent.com/69369181/205746397-087a0893-43af-4c77-b35d-011983b61ffe.png">

**Comment by s4hm4d** [comment]
All go tools will be installed in GOPATH. Maybe it installed in `$HOME/go`
And you can add it to your path by putting this in your profile:
`export GOPATH=$HOME/go`

**Comment by Jiaxing-Zheng** [comment]
@s4hm4d  
![Uploading image.png…]()
how to fix it?
